apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/tonal-justice-348701/static-site@sha256:1bea8f9c53cc53f3172168f914050738d6eb6f4d2431ea0ab6b0c170d47e12d3
        ports:
        - containerPort: 80
